@root = http://127.0.0.1:5002/api

### Get all restaurants
GET {{root}}/restaurant

### Get a restaurant by id
GET {{root}}/restaurant/1

### Create a restaurant
POST {{root}}/restaurant
Content-Type: application/json

{
    "name": "test restaurant"
}

### Delete a restaurant by id
DELETE {{root}}/restaurant/1

### Update a restaurant
PUT {{root}}/restaurant
Content-Type: application/json

{
    "id": 1,
    "name": "a different name"
}

