### Get all restaurants
GET {{root}}/restaurant

### Get a restaurant by id
GET {{root}}/restaurant/2

### Create a restaurant
POST {{root}}/restaurant
Content-Type: application/json

{
    "name": "test restaurant"
}

### Delete a restaurant by id
DELETE {{root}}/restaurant/1
