name: Web Frontend

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: src/frontends/web/spiza-restaurant/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/frontends/web/spiza-restaurant/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./src/frontends/web/spiza-restaurant
        run: npm install

      - name: Build
        working-directory: ./src/frontends/web/spiza-restaurant
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: src/frontends/web/spiza-restaurant/build/
          
  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
